document: meta-test
version: 1
name: nc
packages:
    rpms:
        - nc
        - fedora-release
        #- redhat-release
        #- centos-release
        - psmisc
        - procps-ng
testdependencies:
    rpms:
        - nc
        - fedora-release
        - psmisc
        - procps-ng
default_module: nspawn
module:
    rpm:
        repos:
            - http://ftp.fi.muni.cz/pub/linux/fedora/linux/development/26/Everything/x86_64/os/
            #- http://ftp.fi.muni.cz/pub/linux/centos/7/os/x86_64/

