document: modularity-testing
version: 1
name: bash
modulemd-url: https://src.fedoraproject.org/modules/memcached/raw/master/f/memcached.yaml
packages:
    rpms:
        - bash
module:
    docker:
        container: docker.io/modularitycontainers/memcached
    rpm:
        repo: https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-26/compose/Server/x86_64/os/
